# Generated by Django 4.1 on 2022-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectsByClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolClass', models.CharField(max_length=5)),
                ('physicalEducation', models.BooleanField(default=False)),
                ('biology', models.BooleanField(default=False)),
                ('math', models.BooleanField(default=False)),
                ('ruLanguage', models.BooleanField(default=False)),
                ('enLanguage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='usersByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('group', models.TextField()),
                ('schoolClassMain', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='db',
        ),
    ]
