# Generated by Django 4.1 on 2022-12-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_subjectsbyclass_usersbytype_delete_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNAME', models.CharField(max_length=10)),
                ('CITY', models.CharField(max_length=10)),
                ('RATING', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='homeworkByClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.IntegerField()),
                ('subjectId', models.IntegerField()),
                ('data', models.CharField(max_length=10)),
                ('homework', models.TextField()),
            ],
            options={
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='marksByUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('subjectId', models.IntegerField()),
                ('data', models.CharField(max_length=30)),
                ('mark', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'marks',
            },
        ),
        migrations.CreateModel(
            name='salesPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNAME', models.CharField(max_length=10)),
                ('CITY', models.CharField(max_length=10)),
                ('COMM', models.IntegerField()),
            ],
            options={
                'db_table': 'SalespeopleOne',
            },
        ),
        migrations.RenameField(
            model_name='usersbytype',
            old_name='schoolClassMain',
            new_name='schoolClass',
        ),
        migrations.RemoveField(
            model_name='usersbytype',
            name='person',
        ),
        migrations.AddField(
            model_name='usersbytype',
            name='user',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterModelTable(
            name='subjectsbyclass',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='usersbytype',
            table='users',
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMT', models.IntegerField()),
                ('ODATE', models.DateField()),
                ('CNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.customers')),
                ('SNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.salespeople')),
            ],
        ),
    ]
