# Generated by Django 4.1 on 2022-12-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_customers_homeworkbyclass_marksbyusers_salespeople_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNAME', models.CharField(max_length=20)),
                ('PRICE', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTITY', models.IntegerField()),
                ('PNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.product')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='ORDER',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='board.orderdetails'),
            preserve_default=False,
        ),
    ]
