# Generated by Django 4.1 on 2022-12-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_product_alter_orders_table_orderdetails_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ORDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.orderdetails'),
        ),
    ]
