# Generated by Django 4.1 on 2022-12-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_orders_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ORDERDETAILS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='board.orderdetails'),
        ),
    ]
