# Generated by Django 4.1 on 2022-12-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_orders_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ORDERDETAILS',
        ),
    ]
