# Generated by Django 4.1 on 2022-12-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_orders_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ORDERDETAILS',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='board.orderdetails'),
            preserve_default=False,
        ),
    ]
